name: baseball

channels:
 - conda-forge
 
dependencies:
- python=3.8
- bokeh
- ipython
- ipykernel
- mkl
- notebook
- numpy
- pandas
- patsy
- pip
- scikit-learn
- scipy
- seaborn
- pip:
  - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3
  - git+https://github.com/jldbc/pybaseball.git#egg=pybaseball
  - pyro-ppl
  - catboost
  - git+https://github.com/malmgrek/gammy.git#egg=gammy
